CREATE OR REPLACE TABLE STG_ECDC_CLEAN AS
SELECT
    DATE AS report_date,
    COUNTRY_REGION AS country,
    CONTINENTEXP AS continent,
    ISO3166_1 AS country_iso,
    CAST(CASES AS NUMBER) AS cases,
    CAST(DEATHS AS NUMBER) AS deaths,
    CAST(POPULATION AS NUMBER) AS population,
    LAST_UPDATE_DATE AS last_update
FROM STG_ECDC_GLOBAL
WHERE CASES IS NOT NULL;
